config/routes.rb
Rails.application.routes.draw do
  root "work_logs#index"

  resources :work_logs

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/work_log.rb
class WorkLog < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/work_logs_controller.rb
class WorkLogsController < ApplicationController
  def index
    @work_logs = WorkLog.all
  end

  def show
    @work_log = WorkLog.find(params[:id])
  end

  def new
    @work_log = WorkLog.new
  end

  def create
    @work_log = WorkLog.new(work_log_params)

    if @work_log.save
      redirect_to @work_log
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @title = "Edit Log"
    @work_log = WorkLog.find(params[:id])
  end

  def update
    @work_log = WorkLog.find(params[:id])

    if @work_log.update(work_log_params)
      redirect_to @work_log
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @work_log = WorkLog.find(params[:id])
    @work_log.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def work_log_params
      params.require(:work_log).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/work_logs_helper.rb
module WorkLogsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Worklogs" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/work_logs/_form.html.erb
<%= form_with model: work_log do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% work_log.errors.full_messages_for(:title).each do |message| %>
      <p style="color: red;"><%= message %></p>
    <% end %>
  </div>
  <div>
    <%= form.label :body %><br>
    <%= form.text_field :body %>
    <% work_log.errors.full_messages_for(:body).each do |message| %>
      <p style="color: red;"><%= message %></p>
    <% end %>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/work_logs/edit.html.erb
<%= link_to "Home", root_path %>
<%= link_to "Back", :back%>
<h1><%= @title %></h1>
<%= render "form", work_log: @work_log %>

app/views/work_logs/index.html.erb
<div>
  <h1>WorkLogs</h1>
  <%= link_to "New Log", new_work_log_path %>
  <ul>
    <% @work_logs.each do |work_log| %>
      <li>
        <p>
          <a href="/work_logs/<%= work_log.id %>">
            <strong><%= work_log.title %></strong>
          </a>
          <br>
          <%= work_log.body %>
          <br>
          <time style="font-size: .8rem"><%= work_log.created_at %></time>
        </p>
      </li>
    <% end %>
  </ul>
</div>

app/views/work_logs/new.html.erb
<%= link_to "Home", root_path %>
<%= link_to "Back", :back%>
<h1>New Log</h1>
<%= form_with model: @work_log do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @work_log.errors.full_messages_for(:title).each do |message| %>
      <p style="color: red;"><%= message %></p>
    <% end %>
  </div>
  <div>
    <%= form.label :body %><br>
    <%= form.text_field :body %>
    <% @work_log.errors.full_messages_for(:body).each do |message| %>
      <p style="color: red;"><%= message %></p>
    <% end %>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/work_logs/show.html.erb
<%= link_to "Home", root_path %>
<%= link_to "Back", :back %>
<h1><%= @work_log.title %></h1>
<time>c: <%= @work_log.created_at %></time>
<p><%= @work_log.body %></p>
<%= link_to "Edit", edit_work_log_path(@work_log) %>
<%= link_to "Delete", work_log_path(@work_log), data: {
  turbo_method: :delete,
  turbo_confirm: "Are you sure?"
} %>